### 实现池化层的正向传播

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

def pool2d(X, pool_size, mode='max'):  
    p_h, p_w = pool_size  # 池的宽高，相当于卷积层里卷积核的宽高。
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))  # 池化后的矩阵大小
    for i in range(Y.shape[0]):   # 纵向遍历
        for j in range(Y.shape[1]):    # 横向遍历
            if mode == 'max':
                Y[i, j] = X[i:i + p_h, j:j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i + p_h, j:j + p_w].mean()  # 注意：mean()要求数据类型为 Long
    return Y



### 验证二维最大池化层和平均池化层的输出

In [2]:
X = torch.tensor([[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]])
print(X)
print(pool2d(X, (2,2)))
print(pool2d(X, (2,2),'avg'))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[4., 5.],
        [7., 8.]])
tensor([[2., 3.],
        [5., 6.]])


### 深度学习框架中，默认将步幅和池化层窗口的大小设置为一样大的，同时填充为零，也就意味着移动的时候不会重叠

In [3]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4)) # 批量数，通道数，高，宽
print(X)
pool2d = nn.MaxPool2d(3) # 这里的3就是池化窗口大小，也就是步幅大小。所以，窗口移动不了。
print(pool2d(X))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])
tensor([[[[10.]]]])


### 我们也可以手动设置步幅和填充

In [4]:
print(X)
pool2d = nn.MaxPool2d(3, padding=1, stride=2) # 这里的3仍然是池化窗口大小，但不是步长大小了。
print(pool2d(X))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])
tensor([[[[ 5.,  7.],
          [13., 15.]]]])


### 我们也可以设定任意大小的矩阵，不一定是正方形。并且横向p和s与纵向p和s也可以随意设置。

In [5]:
X = torch.arange(64, dtype=torch.float32).reshape((1,1,8,8)) # 批量数，通道数，高，宽
print(X)
pool2d = nn.MaxPool2d((5,3), padding=(2,1), stride=(2,3)) # 这里的3仍然是池化窗口大小，但不是步长大小了。
print(pool2d(X))

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11., 12., 13., 14., 15.],
          [16., 17., 18., 19., 20., 21., 22., 23.],
          [24., 25., 26., 27., 28., 29., 30., 31.],
          [32., 33., 34., 35., 36., 37., 38., 39.],
          [40., 41., 42., 43., 44., 45., 46., 47.],
          [48., 49., 50., 51., 52., 53., 54., 55.],
          [56., 57., 58., 59., 60., 61., 62., 63.]]]])
tensor([[[[17., 20., 23.],
          [33., 36., 39.],
          [49., 52., 55.],
          [57., 60., 63.]]]])


### 在多通道进行计算

In [16]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4))
X = torch.cat((X,X+1), 1)
# cat()是将两个张量进行拼接的函数，(X,X+1)代表要拼接的两个矩阵，0代表竖着拼接，如果是1则代表横着拼接。
print(X)
pool2d = nn.MaxPool2d(2)
print(pool2d(X))

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])
